### ISSUE TITLE
Could not create Resourse Pack.

### ISSUE THREAD

**Issue by ZanJoye** [wode490390/Radio#12]
2022-12-22 13:20:33.683 [Batching Executor] ERROR - Failed to batch packets
java.lang.AbstractMethodError: cn.wode490390.nukkit.radio.resourcepack.MusicResourcePack.getEncryptionKey()Ljava/lang/String;
	at cn.nukkit.network.protocol.ResourcePacksInfoPacket.a(ResourcePacksInfoPacket.java:29) ~[pm.jar:?]
	at cn.nukkit.network.protocol.ResourcePacksInfoPacket.encode(ResourcePacksInfoPacket.java:35) ~[pm.jar:?]
	at cn.nukkit.network.protocol.DataPacket.tryEncode(DataPacket.java:52) ~[pm.jar:?]
	at cn.nukkit.network.session.RakNetPlayerSession.sendPacket(RakNetPlayerSession.java:14) ~[pm.jar:?]
	at cn.nukkit.network.BatchingHelper.a(BatchingHelper.java:51) ~[pm.jar:?]
	at cn.nukkit.network.BatchingHelper.lambda$batchPackets$1(BatchingHelper.java:74) ~[pm.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_351]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_351]

**Comment by ZanJoye** [comment]
Run on PM1E

**Comment by XackiGiFF** [comment]
Add to MusicResourcePack this:

```
    public void saveToResourcePacksFolder(Path resourcePacksFolder) throws IOException {
        // Make name using UUID
        String fileName = this.uuid.toString() + ".mcpack";

        // Save in /resource_packs/
        Path outputPath = resourcePacksFolder.resolve(fileName);
        Files.write(outputPath, this.data);

        // Log
        System.out.println("Resource pask saved: " + outputPath);
    }
```


And in Main class on Enable AFTER this "133            this.getServer().getPluginManager().registerEvents(this, this);":
```
            // Get /resource_packs/
            Path serverPath = Paths.get(this.getServer().getFilePath());
            Path resourcePacksFolder = serverPath.resolve("resource_packs");

            // Save in /resource_packs/
            for (ResourcePack pack : packs) {
                if (pack instanceof MusicResourcePack) {
                    try {
                        ((MusicResourcePack) pack).saveToResourcePacksFolder(resourcePacksFolder);
                    } catch (IOException e) {
                        this.getLogger().error("Error while saving:", e);
                    }
                }
            }
```


It will save RP in folder and we can reload server again for send RP from Nukkit path
Work for me.

**Comment by XackiGiFF** [comment]
> Run on PM1E

My method works on Nukkit-MOT, but my method is not great
